include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.config.dart'
  errors:
    # allow having TODOs in the code
    todo: ignore

formatter:
  page_width: 80

linter:
  rules:
    prefer_single_quotes: true
    eol_at_end_of_file: true
    #    use_super_parameters: true

    # IDENTIFIER
    camel_case_types: true
    camel_case_extensions: true
    library_prefixes: true
    constant_identifier_names: true

    # ORDERING
    directives_ordering: true

    # FORMATTING
    curly_braces_in_flow_control_structures: true
    require_trailing_commas: true
    trailing_commas: preserve

    # COMMENT
    slash_for_doc_comments: true
    comment_references: true

    # NULL
    avoid_init_to_null: true

    # STRING
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_brace_in_string_interps: true

    # COLLECTIONS
    prefer_collection_literals: true
    prefer_is_empty: true

    # FUNCTIONS
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true

    # MEMBERS
    unnecessary_getters_setters: true

    # CONSTRUCTORS
    prefer_initializing_formals: true
    empty_constructor_bodies: true
    unnecessary_new: true

    # CONTEXT
    use_build_context_synchronously: false